the-way:
  core:
    log: true
  log:
    level: 0
  server:
    enabled: true
    port: 8081
    path: /api
    swagger:
      enabled: false
      path: /swagger
      filePath: './swagger.json'
    security:
      user-key: A2345678901234567890123456789012
      token-key: B2345678901234567890123456789034
      token-expiration: '3 days'
    file:
      enabled: false
      fallback: false
      full: false
      path: ''
      static: 
        path: ''
        full: false
      assets: 
        path: ''
        full: false